spring:
  application:
    name: consultorio-webaap


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5434/consultorio
    username: admin
    password: admin


  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    defer-datasource-initialization: true

logging:
  level:
    sql: debug

